// USER ACTION TYPES
export const CONNECT = 'CONNECT'
export const SET_TOKEN = 'SET_TOKEN'
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO'
export const SAVE_USER = 'SAVE_USER'
export const UPDATE_USER = 'UPDATE_USER'
export const INIT_STATE = 'INIT_STATE'
export const UPDATE_LAST_ACTION = 'UPDATE_LAST_ACTION'
export const SET_PATHNAME = 'SET_PATHNAME'

// TRIP ACTION TYPES
export const SAVE_TRIP = 'SAVE_TRIP'
export const SET_TRIPS = 'SET_TRIPS'
export const SET_CURRENT_TRIP = 'SET_CURRENT_TRIP'
export const SET_TRIP_DESIRED_PLACE = 'SET_TRIP_DESIRED_PLACE'
export const READ_DRIVER_TRIPS = '';